### ISSUE TITLE
Error: tunneling socket could not be established, cause=socket hang up

### ISSUE THREAD

**Issue by MaxCDon** [genffy/nextjs-chatgpt-demo#1]
when I sent message，throw this error

Error: tunneling socket could not be established, cause=socket hang up

**Comment by genffy** [comment]
> when I sent message，throw this error
> 
> Error: tunneling socket could not be established, cause=socket hang up

are you clone code and run local ?  pls check https://github.com/genffy/nextjs-chatgpt-demo#dev
